[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "pytz>=2025.2",
    "requests>=2.32.3",
    "python-telegram-bot>=21.0.1",
]
